# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_urll_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='urll',
            name='hight_recurcian',
            field=models.IntegerField(default=0),
        ),
    ]
